### ISSUE TITLE
nze_hvac is failing in 3.1

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/openstudio-ee-gem#9]
Test again once I get model articulation measures working and see if this works as well.

**Comment by DavidGoldwasser** [comment]
I just ran this dashboard using ruby with master checkout of standards and develop checkout of openstudio-extension gem and the error went away. @tijcolem so as long as final install has updated gems this repo is fine. I'm currently running same test on model articulation repo.

**Comment by DavidGoldwasser** [comment]
Never mind :( After the test I somehow still had old dashboard in my machine. @tijcolem and @mdahlhausen this is still failing with most current standards gem.

**Comment by DavidGoldwasser** [comment]
The sizing run seems to have worked, but there is this odd error at end of the `openstudio-standards.log` file

```
DEBUG Starting simulation here: /Users/dgoldwas/Documents/GitHub/NREL/openstudio-ee-gem/lib/measures/nze_hvac/tests/output/test_office_vrf_doas_per_story/SizingRun.
INFO  Running simulation /Users/dgoldwas/Documents/GitHub/NREL/openstudio-ee-gem/lib/measures/nze_hvac/tests/output/test_office_vrf_doas_per_story/SizingRun.
DEBUG Running with OS 2.x WorkflowJSON.
DEBUG Successfully ran command: '"/Applications/OpenStudio-3.1.0-rc1/bin/openstudio" run -w "/Users/dgoldwas/Documents/GitHub/NREL/openstudio-ee-gem/lib/measures/nze_hvac/tests/output/test_office_vrf_doas_per_story/SizingRun/in.osw"'
INFO  Finished run.
DEBUG Dictionary Built
ERROR The run did not finish and had following errors:```

**Comment by DavidGoldwasser** [comment]
@mdahlhausen Not sure if this is still open, but there is UH post about this measure with system type argument selection of hvac_system_type_choice. If there isn't a test of this system type in measure test, then I'll add it when doing 3.2 tests. I may go back and test 3.1 installer as well.
https://unmethours.com/question/53648/nze-hvac-measure-could-not-find-argument-error/?comment=53724#post-id-53724

**Comment by mdahlhausen** [comment]
@DavidGoldwasser I can't recreate the error for the nze hvac measure in several different openstudio and openstudio-standards versions.  Can you?
